<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Superior</name>
   <tag></tag>
   <elementGuidId>ab665e50-e66d-4200-a634-fc3ca5150add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='superior']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
