<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AbrirPopup</name>
   <tag></tag>
   <elementGuidId>d6af79b1-2f10-47a5-9004-fe6439e673d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//input[@id='buttonSimple']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
