<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Esportes</name>
   <tag></tag>
   <elementGuidId>9b1602a9-fa92-405d-b6b1-24f528fbad7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ancestor::div[@id=&quot;descEsportes&quot;]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
