<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Escolaridade</name>
   <tag></tag>
   <elementGuidId>d008d613-fd85-4acd-bdef-fdcfce43dd14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ancestor::div[@id=&quot;descEscolaridade&quot;]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
